name: CI/CD
on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: "Testing"
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run testing script
        run: bash ./scripts/test.sh
        env:
          TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL: false
      - name: Build And Push images
        run: |
          echo {{ '${{ secrets.GH_TOKEN }}' }} | docker login https://docker.pkg.github.com -u {{ cookiecutter.github_username }} --password-stdin
          bash ./scripts/build-push.sh
        env:
          TAG: staging
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: {% raw %}"${{ secrets.SSH_KEY }}"{% endraw %}
          name: id_rsa
          known_hosts: {% raw %}"${{ secrets.KNOWN_HOSTS }}"{% endraw %}
      - name: Install Required packages
        run: pip install docker-auto-labels paramiko
      - name: Install Docker Auto labels
        run: pip install docker-auto-labels
      - name: Deploy
        run: bash ./scripts/deploy.sh
        env:
          DOCKER_HOST: "ssh://${{ '{{ secrets.DOCKER_HOST }}' }}"
          DOMAIN: {{ cookiecutter.domain_staging }}
          STACK_NAME: {{ cookiecutter.docker_swarm_stack_name_staging }}
          TAG: staging
          TRAEFIK_TAG: {{ cookiecutter.traefik_constraint_tag_staging }}
